# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_myentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=300)),
            ],
        ),
    ]
