# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_mytags'),
    ]

    operations = [
        migrations.AddField(
            model_name='myentry',
            name='tags',
            field=models.ManyToManyField(to='blog.MyTags'),
        ),
    ]
