# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 10:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_myentry_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myentry',
            name='tags',
        ),
        migrations.DeleteModel(
            name='MyTags',
        ),
    ]
