# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 14:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_auto_20161214_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='myentry',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myentry',
            name='tags',
            field=models.ManyToManyField(to='tags.Tag'),
        ),
    ]
