# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-05 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20161217_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myentry',
            name='tags',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='tags.Tag'),
        ),
    ]
